# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3488c17ab9c8f6871614b9bf280f8c1c8db8b6167fb052309414836aea55f4da07c6a05fd27486df9dbc6c198e2d76e0aaa17631fc5b6898bfb7325c2ee092a5

test:
  secret_key_base: f5a3010f04dbdadd969ed6275f7236216f0552b116d6be5a92e51a7185658ef10adf2cface5ab326fc7369204de48dde9ded6c45ea21be3ad7031785f6ea74ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
